"""
PDF Report Generator for SENTINEL AI.
Produces a professional security report using fpdf2.
"""

import io
from datetime import datetime
from typing import Dict, List

from fpdf import FPDF, XPos, YPos


# ── Colour palette ────────────────────────────────────────────────────────────
C_BG        = (15,  17,  23)   # #0f1117
C_CARD      = (13,  18,  33)   # #0d1221
C_ACCENT    = (0,   212, 255)  # #00d4ff
C_GREEN     = (74,  222, 128)  # #4ade80
C_RED       = (248, 113, 113)  # #f87171
C_ORANGE    = (249, 115,  22)  # #f97316
C_TEXT      = (226, 232, 240)  # #e2e8f0
C_MUTED     = (100, 116, 139)  # #64748b
C_WHITE     = (255, 255, 255)

SEV_COLORS  = {
    "Critical": (239,  68,  68),
    "High":     (249, 115,  22),
    "Medium":   (234, 179,   8),
    "Low":      ( 74, 222, 128),
}


class SentinelPDF(FPDF):
    def header(self):
        # Dark background strip
        self.set_fill_color(*C_BG)
        self.rect(0, 0, 210, 18, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*C_ACCENT)
        self.set_y(5)
        self.cell(0, 8, "SENTINEL AI  —  Autonomous Security Report", align="C")
        self.set_draw_color(*C_ACCENT)
        self.set_line_width(0.4)
        self.line(10, 18, 200, 18)
        self.ln(6)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*C_MUTED)
        self.cell(0, 6,
                  f"Generated by SENTINEL AI  •  {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}  •  Page {self.page_no()}",
                  align="C")

    # ── Helpers ───────────────────────────────────────────────────────────────
    def section_title(self, title: str, icon: str = ""):
        self.ln(4)
        self.set_fill_color(*C_CARD)
        self.set_draw_color(*C_ACCENT)
        self.set_line_width(0.3)
        self.rect(10, self.get_y(), 190, 9, "FD")
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*C_ACCENT)
        self.set_x(13)
        self.cell(0, 9, f"  {icon}  {title.upper()}" if icon else f"  {title.upper()}")
        self.ln(11)

    def kv_row(self, key: str, value: str, val_color=None):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*C_MUTED)
        self.set_x(14)
        self.cell(45, 6, key)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*(val_color or C_TEXT))
        self.multi_cell(0, 6, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def severity_badge(self, severity: str):
        color = SEV_COLORS.get(severity, C_MUTED)
        self.set_fill_color(*color)
        self.set_text_color(*C_WHITE)
        self.set_font("Helvetica", "B", 8)
        self.set_x(14)
        self.cell(28, 6, f"  {severity.upper()}  ", fill=True, align="C")
        self.ln(8)

    def code_block(self, code: str, max_lines: int = 30):
        lines = code.strip().splitlines()[:max_lines]
        if len(code.strip().splitlines()) > max_lines:
            lines.append(f"... ({len(code.strip().splitlines()) - max_lines} more lines)")
        self.set_fill_color(7, 10, 16)
        self.set_draw_color(*C_MUTED)
        self.set_line_width(0.2)
        block_h = len(lines) * 4.5 + 4
        self.rect(12, self.get_y(), 186, block_h, "FD")
        self.set_font("Courier", "", 7.5)
        self.set_text_color(*C_TEXT)
        self.set_x(14)
        self.set_y(self.get_y() + 2)
        for line in lines:
            self.set_x(14)
            self.cell(0, 4.5, line[:120])
            self.ln(4.5)
        self.ln(3)

    def divider(self):
        self.set_draw_color(*C_MUTED)
        self.set_line_width(0.2)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)


def generate_pdf_report(result: Dict, source: str = "") -> bytes:
    """
    Build a PDF security report from the analysis result dict.
    Returns raw PDF bytes.
    """
    findings: List[Dict] = result.get("findings", [])
    risk      = result.get("risk_score", 0)
    verdict   = result.get("reviewer_verdict", "STILL VULNERABLE")
    status    = result.get("final_status", "Not Secure")
    conf      = result.get("confidence_score", 0)
    iters     = result.get("iterations", 0)

    pdf = SentinelPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.set_margins(10, 22, 10)
    pdf.set_fill_color(*C_BG)
    pdf.add_page()

    # ── Cover block ───────────────────────────────────────────────────────────
    pdf.set_fill_color(*C_BG)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.set_font("Helvetica", "B", 26)
    pdf.set_text_color(*C_ACCENT)
    pdf.ln(4)
    pdf.cell(0, 14, "SECURITY ANALYSIS REPORT", align="C")
    pdf.ln(10)

    # Status badge
    badge_color = C_GREEN if status == "Secure" else C_RED
    pdf.set_fill_color(*badge_color)
    pdf.set_text_color(*C_WHITE)
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_x(70)
    pdf.cell(70, 10, f"  {status.upper()}  ", fill=True, align="C")
    pdf.ln(12)

    # Meta grid
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*C_MUTED)
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    meta = [
        ("Generated", ts),
        ("Source", source or "Pasted Code"),
        ("Risk Score", f"{risk}/100"),
        ("Findings", str(len(findings))),
        ("Fix Confidence", f"{conf}%"),
        ("Review Iterations", str(iters)),
        ("Verdict", verdict),
    ]
    for k, v in meta:
        pdf.kv_row(k, v)

    pdf.divider()

    # ── Executive Summary ─────────────────────────────────────────────────────
    pdf.section_title("Executive Summary", "📋")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*C_TEXT)
    pdf.set_x(14)

    if not findings:
        summary = "No vulnerabilities were detected. All analyzed files passed security checks."
    else:
        sev_counts: Dict[str, int] = {}
        for f in findings:
            s = f.get("severity", "Unknown")
            sev_counts[s] = sev_counts.get(s, 0) + 1
        sev_str = ", ".join(f"{v} {k}" for k, v in sev_counts.items())
        passed  = sum(1 for f in findings if f.get("validation") == "PASS")
        summary = (
            f"SENTINEL AI identified {len(findings)} vulnerability finding(s) across "
            f"{len({f['file_path'] for f in findings})} file(s): {sev_str}. "
            f"{passed} of {len(findings)} findings were successfully patched and validated. "
            f"Overall risk score: {risk}/100. Final verdict: {verdict}."
        )
    pdf.multi_cell(0, 5.5, summary, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # ── Findings ──────────────────────────────────────────────────────────────
    if findings:
        pdf.section_title("Vulnerability Findings", "🔍")

        for idx, f in enumerate(findings, 1):
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(*C_TEXT)
            pdf.set_x(14)
            pdf.cell(0, 7, f"{idx}. {f.get('type', 'Unknown')}  —  {f.get('file_path', '')}")
            pdf.ln(7)

            pdf.severity_badge(f.get("severity", "Unknown"))

            # CVSS score if present
            if f.get("cvss_score"):
                pdf.kv_row("CVSS Score", f"{f['cvss_score']} / 10.0  ({f.get('cvss_vector', '')})")

            pdf.kv_row("Explanation", f.get("explanation", ""))
            pdf.kv_row("Exploit Payload", f.get("exploit_payload", "N/A"))
            pdf.kv_row("Validation", f.get("validation", "N/A"),
                       val_color=C_GREEN if f.get("validation") == "PASS" else C_RED)

            if f.get("fix_explanation"):
                pdf.kv_row("Fix Applied", f.get("fix_explanation", ""))

            # Original code
            if f.get("original_code"):
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*C_RED)
                pdf.set_x(14)
                pdf.cell(0, 5, "Original (Vulnerable) Code:")
                pdf.ln(5)
                pdf.code_block(f["original_code"])

            # Patched code
            if f.get("patched_code"):
                pdf.set_font("Helvetica", "B", 8)
                pdf.set_text_color(*C_GREEN)
                pdf.set_x(14)
                pdf.cell(0, 5, "Patched (Secure) Code:")
                pdf.ln(5)
                pdf.code_block(f["patched_code"])

            pdf.divider()

    # ── Exploit Output ────────────────────────────────────────────────────────
    if result.get("exploit_script") and result["exploit_script"].strip() != "# No exploits generated":
        pdf.section_title("Exploit Proof", "💥")
        pdf.kv_row("Payload", result.get("exploit_payload", "N/A"))
        if result.get("exploit_proof"):
            pdf.kv_row("Proof Statement", result["exploit_proof"])
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*C_RED)
        pdf.set_x(14)
        pdf.cell(0, 5, "Exploit Script:")
        pdf.ln(5)
        pdf.code_block(result.get("exploit_script", ""), max_lines=25)
        pdf.kv_row("Against Vulnerable Code", result.get("exploit_vulnerable_result", ""))
        pdf.kv_row("Against Patched Code",    result.get("exploit_patched_result", ""))
        pdf.divider()

    # ── Validation ────────────────────────────────────────────────────────────
    pdf.section_title("Validation Result", "✅")
    pdf.kv_row("Verdict",          verdict,
               val_color=C_GREEN if verdict == "SECURE" else C_RED)
    pdf.kv_row("Confidence Score", f"{conf}%")
    pdf.kv_row("Iterations",       str(iters))
    if result.get("reviewer_justification"):
        pdf.kv_row("Justification", result["reviewer_justification"][:500])

    # ── Footer note ───────────────────────────────────────────────────────────
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(*C_MUTED)
    pdf.set_x(14)
    pdf.multi_cell(0, 5,
        "This report was generated automatically by SENTINEL AI. "
        "Results should be reviewed by a qualified security professional before taking action.",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    return bytes(pdf.output())
